threads=50
rampup=120
loops=2

# Umbrales APDEX para el reporte HTML
# Tiempo máximo para que la solicitud sea satisfactoria
jmeter.reportgenerator.apdex_satisfied_threshold=500
# Tiempo máximo para que la solicitud sea tolerable
jmeter.reportgenerator.apdex_tolerated_threshold=1000
# Tiempo máximo para que la solicitud sea intolerable
jmeter.reportgenerator.apdex_frustrated_threshold=2000